### ISSUE TITLE
How to write a post route?

### ISSUE THREAD

**Issue by subhendukundu** [hodgef/apiker#133]
Love what you are building, but I am not able to figure out how to write a route for a post API.

```
const routes = {
  "/users/:id/counter": getUserCounter
};
```
Where do we define the type of request?

**Comment by hodgef** [comment]
Update: Check out the [documentation](https://hodgef.com/apiker/) for detailed Getting Started instructions.


________

Hey @subhendukundu,

Cloudflare Workers (therefore Apiker) will respond to any request to this route, regardless of the method. Apiker will also parse the data sent (if any) and make it available in your route's handler.

For example:
```js
import { res, res_400 } from "apiker";

export const myRouteHandler = async ({
  request, // https://developers.cloudflare.com/workers/runtime-apis/request/
  body, // The body of your request, such as form params or plaintext, depending on request content-type
  headers, // Request headers. Response headers are located at `apiker.responseHeaders`
  matches, // Your query params and route parts
  state // The state method used to interact with permanent storage (check the docs for more info)
}) => {
  // If we want to allow POST only, we explicitly check for it :
  if(request.method !== "POST"){
     // returns 400 Bad Request error. You can also use `res("Invalid Method", 405)`
     // https://github.com/hodgef/apiker/blob/master/src/components/Response/Response.ts#L10
     return res_400();
  }

  // We'll return the request body passed, for example POST form parameters
  // `res` and `res_000` functions respond with JSON. To respond with raw text you can use `resRaw`
  // https://github.com/hodgef/apiker/blob/master/src/components/Response/Response.ts#L23
  return res({ body });
};
```
```js
const routes = {
  "/users/myroute": myRouteHandler
};
```


Here's where the `body` parsing is done:
https://github.com/hodgef/apiker/blob/master/src/components/Request/Request.ts#L76

Here's an example of a handler for a POST route:
https://github.com/hodgef/apiker/blob/master/src/components/Auth/registerUser.ts#L9
![image](https://user-images.githubusercontent.com/25509135/180663417-1f0de73f-9aef-4d7e-9a83-03a97b8349bc.png)

As you can see, in the register handler's code I don't filter by method because it's not strictly necessary, all I look for is for body parameters.

Let me know if you have any questions regarding this.

Regards,
Francisco Hodge
